### PR TITLE
Update requirements of `clickhouse-connect`

### PR DESCRIPTION
**Pull request by saurabhbikram**
Using version 0.5 or above breaks the `http` connection for clickhouse. Adding anything in `custom_settings` in profiles.yml leads to the following error when you run `dbt debug`

```
1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:
                                              
  >Database Error
  __init__() got an unexpected keyword argument 'max_insert_threads'
```

### CODE REVIEW

**Comment by genzgd** [comment]
This should work correctly in 1.3.2?

**Comment by genzgd** [comment]
All integration tests pass on the current main branch (which matches releasee 1.3.3) with ClickHouse Connect 0.5.5, including with custom settings.  I don't *think* we can backport this requirements fix to earlier versions?

**Comment by saurabhbikram** [comment]
@genzgd  it didn't work for me with these settings

```
dbt version: 1.3.2
python version: 3.9.2
```

**Comment by genzgd** [comment]
I can definitely reproduce in dbt-clickhouse 1.3.1, but not later releases.  What is your dbt-clickhouse version?

**Comment by saurabhbikram** [comment]
I was on 1.3.1 indeed, updating to 1.3.3 fixes it. Thanks, I will close this PR.

**Comment by genzgd** [comment]
No problem, I apologize for the breaking change and I sincerely hope it will be the last one that affects dbt-clickhouse.
